//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class house
    {
        public int id { get; set; }
        public string name { get; set; }
        public string adress { get; set; }
        public Nullable<decimal> rent_price { get; set; }
        public Nullable<int> flat_status { get; set; }
    
        public virtual status status { get; set; }
    }
}
